version: "2"

services:
  ingress:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  depict:
    image: simolecule/cdkdepict:latest
    command: ["--server.forward-headers-strategy=framework"]
